name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Backend - Install Dependencies
      run: npm ci
      working-directory: ./backend

    - name: Backend - Run Linter
      run: npm run lint --if-present
      working-directory: ./backend

    - name: Backend - Run All Tests with Coverage
      run: npx jest --coverage
      working-directory: ./backend

    - name: Frontend - Install Dependencies
      run: npm ci
      working-directory: ./frontend

    - name: Frontend - Build
      run: npm run build
      working-directory: ./frontend
